### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by ghummer**
this way it works with https://kit.svelte.dev

### CODE REVIEW

**Comment by ivandotv** [comment]
Thanks for trying to contribute!
Unfortunately, tt can't be switched to a module just like that.
https://github.com/ivandotv/radio-browser-api/issues/59
However, I've added the `module` export so it might get picked up by the svelte build process.
Let me know if it works.

**Comment by ghummer** [comment]
Hey, unfortunately I'm still facing the same problem. :-/

Will follow #59 to see if it gets resolved. Thanks for the work though!

**Comment by ivandotv** [comment]
@ghummer Can you try the latest version from `npm` It is fixed now. Module bundlers should pick up `module` version, and node also when directly importing.

**Comment by ghummer** [comment]
> @ghummer Can you try the latest version from `npm` It is fixed now. Module bundlers should pick up `module` version, and node also when directly importing.

works a charm! thanks! :+1:

**Pull request closed without merging**
